import fs from 'node:fs';
const de = fs.readFileSync('C:/Users/Usuario/Desktop/ranking games/DESIGN.md','utf8');
const frase = de.slice(de.indexOf('Lo que estructura la tabla son sus propias líneas'), de.indexOf('Medido: al transparentarla'));
console.log('### el parrafo §3.3 tal cual esta ###');
console.log(frase);
console.log('');
let fail=0;
const chk=(c,l,x)=>{ if(!c) fail++; console.log(`  ${c?'PASS':'FAIL'}  ${l}${x!==undefined?'  -> '+x:''}`); };
chk(frase.includes('`0,7rem` de aire entre juegos'), 'los 0,7rem estan, con backticks (era lo que faltaba en mi guarda)');
chk(/0,95rem/.test(frase), 'y la razon de por que van por debajo del movil');
chk(/un margen no pinta/.test(frase), 'y por que eso no puede ser pintura');
chk(/4 % de opacidad|no basta para reencontrar/.test(frase), 'y el motivo: el pelo no basta para reencontrar la fila');
chk(/segundo canal/.test(frase), 'y que es un segundo canal, no un sustituto');
console.log(`\n=== ${fail===0?'TODO VERDE':fail+' FAIL'} ===`);
process.exit(fail===0?0:1);
